# Generated by Django 4.1.5 on 2023-01-29 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginstance',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular blog', primary_key=True, serialize=False),
        ),
    ]
