# Generated by Django 4.1.5 on 2023-02-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
