# Generated by Django 4.1.5 on 2023-02-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cover',
        ),
    ]
